# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Official DOc on GitHub Workflow Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

# Conda based env testing: https://github.com/conda-incubator/setup-miniconda
name: Run tests

on:

  # Trigger the workflow on push but only for the master branch
  push:
    branches:
      - master

  # Trigger current workflow on PR from ANY branch
  pull_request:
    branches:
      - '*'

  # Trigger every
  schedule:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
    # i.e. this runs every day at 4:33AM for the master branch.
    - cron: '33 4 * * *'

env:
  # Even when given -y, apt will still sometimes hang at a prompt if a package
  # has clarifications to ask; DEBIAN_FRONTEND=noninteractive prevents that,
  # This will be defined for non-debian platforms below too, but there's no harm in that.
  # (TravisCI quietly defined this on all their platforms, but we have to give it manually on GithubCI.)
  DEBIAN_FRONTEND: 'noninteractive'

jobs:
  ultra_matrix_test:
    name: Ultra Matrix Test of (Python ${{ matrix.python-version }} on ${{ matrix.os }})

    # Matrix driven OS
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      # Step 0: Checkout code.
      - uses: actions/checkout@v2

      # Step 1: List conda info.
      - name: List all current repository files and modification date
        # Shell command
        shell: bash -l {0}
        # Parameters.
        run: |
          ls -lasth
          pwd

      # Step 2: Ubuntu
      - name: Install Conda Env Ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ads_venv
          auto-update-conda: true
          environment-file: environment_Linux.yml

      # Step 2: OS X
      - name: Install Conda Env macOS
        if: matrix.os == 'macos-latest'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ads_venv
          auto-update-conda: true
          environment-file: environment_macOS.yml

      # Step 2: Windows
      - name: Install Conda Env Windows
        if: matrix.os == 'windows-latest'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ads_new
          auto-update-conda: true
          environment-file: environment_Windows.yml

      # Step 3: List conda info, conda list packages
      - name: Conda info and list
        # List
        shell: pwsh
        run: |
          conda info
          conda list

      # Step 4:
      - name: Installation of the repository
        run: |
          cd /home/runner/work/axondeepseg/axondeepseg/
          pip install --verbose -e .
          pip install python-coveralls

      # Step 5: Conda list packages
      - name: Conda list post installation
        # List
        shell: pwsh
        run: conda list

      # Step 6: Lint
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # Step 7: Test
      - name: Test with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
        run: |
          py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
          coveralls --service=github

  coveralls:
    needs: ultra_matrix_test
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}