# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# Official DOc on GitHub WOrkflow Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Run tests

on:

  # Trigger the workflow on push but only for the master branch
  push:
    branches:
      - master

  # Trigger current workflow on PR from ANY branch
  pull_request:
    branches:
      - '*'

  # Trigger every
  schedule:
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onschedule
    # i.e. this runs every day at 4:33AM for the master branch.
    - cron: '33 4 * * *'

env:
  # Even when given -y, apt will still sometimes hang at a prompt if a package
  # has clarifications to ask; DEBIAN_FRONTEND=noninteractive prevents that,
  # This will be defined for non-debian platforms below too, but there's no harm in that.
  # (TravisCI quietly defined this on all their platforms, but we have to give it manually on GithubCI.)
  DEBIAN_FRONTEND: 'noninteractive'

jobs:

  # Job 1: Windows testing.
  test_win:
    name: Test AxonDeepSeg on Windows Server 2019
    runs-on: windows-latest

  # Job 2: Mac Catalina testing.
  test_mac_10:
    name: Test AxonDeepSeg on macOS Catalina
    runs-on: macos-10.15

  # Job 3: Mac Big Sur testing.
  test_mac_11:
    name: Test AxonDeepSeg on macOS Big Sur
    runs-on: macos-11.0

  test_ubuntu_18:
    name: Ubuntu Latest
    runs-on: ubuntu-latest

  test_ubuntu_20:

    name: Ubuntu Latest
    runs-on: ubuntu-latest

    # Matrix testing
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        test-name:
          - integration-test
    steps:
      # Step 1: Checkout code.
      - uses: actions/checkout@v2
      # Step 2: Setup python version.
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # Step 3:
      - name: Installation of MiniConda
        run: |
          echo "Installation of MiniConda"
          cd ~
          if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o ~/miniconda.sh; fi
          if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh; fi
          bash ~/miniconda.sh -b -p $HOME/miniconda
          echo ". ~/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
          source ~/.bashrc
          yes | conda create -n ads_venv python=3.7
          conda activate ads_venv
          echo "Installation of the repository"
          cd ~/build/neuropoly/axondeepseg
          pip install -e .
          pip install python-coveralls  # Add me to install python-coveralls
      # Step 4:
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      # Step 5:
      - name: Test with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
        run: |
          py.test . -v --cov AxonDeepSeg/ --cov-report term-missing
          coveralls --service=github

  coveralls:
    needs: test_ubuntu_18
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --finish
        env: